// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeBeforeThePatient.Data;

#nullable disable

namespace PracticeBeforeThePatient.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.AssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("ClassId", "ScenarioId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.ClassEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.ClassStudentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("StudentUserId");

                    b.HasIndex("ClassId", "StudentUserId")
                        .IsUnique();

                    b.ToTable("ClassStudents");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.ClassTeacherEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("TeacherUserId");

                    b.HasIndex("ClassId", "TeacherUserId")
                        .IsUnique();

                    b.ToTable("ClassTeachers");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.ScenarioEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.SubmissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeFeedback")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GradedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GradedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmissionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GradedByUserId");

                    b.HasIndex("StudentUserId");

                    b.HasIndex("AssignmentId", "StudentUserId")
                        .IsUnique();

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SsoSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SsoSubject")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.AssignmentEntity", b =>
                {
                    b.HasOne("PracticeBeforeThePatient.Data.Entities.UserEntity", "AssignedBy")
                        .WithMany("AssignedAssignments")
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PracticeBeforeThePatient.Data.Entities.ClassEntity", "Class")
                        .WithMany("Assignments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticeBeforeThePatient.Data.Entities.ScenarioEntity", "Scenario")
                        .WithMany("Assignments")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("Class");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.ClassEntity", b =>
                {
                    b.HasOne("PracticeBeforeThePatient.Data.Entities.UserEntity", "CreatedBy")
                        .WithMany("CreatedClasses")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.ClassStudentEntity", b =>
                {
                    b.HasOne("PracticeBeforeThePatient.Data.Entities.UserEntity", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PracticeBeforeThePatient.Data.Entities.ClassEntity", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticeBeforeThePatient.Data.Entities.UserEntity", "Student")
                        .WithMany("StudentEnrollments")
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.ClassTeacherEntity", b =>
                {
                    b.HasOne("PracticeBeforeThePatient.Data.Entities.UserEntity", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PracticeBeforeThePatient.Data.Entities.ClassEntity", "Class")
                        .WithMany("Teachers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticeBeforeThePatient.Data.Entities.UserEntity", "Teacher")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.SubmissionEntity", b =>
                {
                    b.HasOne("PracticeBeforeThePatient.Data.Entities.AssignmentEntity", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticeBeforeThePatient.Data.Entities.UserEntity", "GradedBy")
                        .WithMany("GradedSubmissions")
                        .HasForeignKey("GradedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PracticeBeforeThePatient.Data.Entities.UserEntity", "Student")
                        .WithMany("SubmittedSubmissions")
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("GradedBy");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.AssignmentEntity", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.ClassEntity", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.ScenarioEntity", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("PracticeBeforeThePatient.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("AssignedAssignments");

                    b.Navigation("CreatedClasses");

                    b.Navigation("GradedSubmissions");

                    b.Navigation("StudentEnrollments");

                    b.Navigation("SubmittedSubmissions");

                    b.Navigation("TeachingAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
